// Generated by Copilot
export default function NotFound() {
  return (
    <div className="container mx-auto py-20 text-center">
      <h1 className="text-4xl font-bold mb-4">Tags Not Found</h1>
      <p className="text-xl">Sorry, tags not found. Please try again later.</p>
    </div>
  );
}
