// Generated by Copilot
export default function NotFound() {
  return (
    <div className="container mx-auto py-20 text-center">
      <h1 className="text-4xl font-bold mb-4">Blog Post Not Found</h1>
      <p className="text-xl">
        The blog post you are looking for does not exist or has been moved.
      </p>
    </div>
  );
}
