// Generated by Copilot
import React from "react";

const Skills: React.FC = () => {
  // Skills data
  const _skills = {
    frontend: [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "JavaScript",
      "HTML/CSS",
    ],
    backend: ["Node.js", "Python", "Express", "FastAPI", "PHP", "Laravel"],
    database: ["PostgreSQL", "MongoDB", "MySQL", "Redis"],
    devops: ["Docker", "Kubernetes", "AWS", "GCP", "CI/CD", "Terraform"],
    others: [
      "Git",
      "RESTful APIs",
      "GraphQL",
      "Microservices",
      "System Design",
    ],
  };

  const _categories = [
    { name: "Frontend", skills: _skills.frontend },
    { name: "Backend", skills: _skills.backend },
    { name: "Database", skills: _skills.database },
    { name: "DevOps", skills: _skills.devops },
    { name: "Others", skills: _skills.others },
  ];

  return (
    <section id="skills" className="py-16 bg-gray-50">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-gray-900">Technical Skills</h2>
          <p className="mt-4 text-lg text-gray-600">
            Technologies and tools I work with
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {_categories.map((category, index) => (
            <div key={index} className="bg-white p-6 rounded-lg shadow-md">
              <h3 className="text-xl font-semibold text-gray-900 mb-4">
                {category.name}
              </h3>
              <div className="flex flex-wrap gap-2">
                {category.skills.map((skill, skillIndex) => (
                  <span
                    key={skillIndex}
                    className="px-3 py-1 bg-blue-100 text-blue-800 text-sm font-medium rounded-full"
                  >
                    {skill}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Skills;
